version: "3.7"

services:

  covenant:
    image: "isaudits/covenant"
    container_name: "covenant"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # Web interface - host:443 to covenant:7443
      - "traefik.tcp.routers.covenantUi.rule=Host(`cov.domain.tld`)"
      - "traefik.tcp.routers.covenantUi.service=covenantUi@docker"
      - "traefik.tcp.services.covenantUi.loadbalancer.server.port=7443"
      - "traefik.tcp.routers.covenantUi.entrypoints=https"
      # HTTP Delivery - host/cov_delivery to covenant:80
      - "traefik.http.routers.covenantDelivery.rule=Host(`cov.domain.tld`) && PathPrefix(`/cov_delivery`)"
      - "traefik.http.routers.covenantDelivery.service=covenantDelivery@docker"
      - "traefik.http.routers.covenantDelivery.entrypoints=https"
      - "traefik.http.services.covenantDelivery.loadbalancer.server.port=80"
      # HTTP Payload Handler - host/cov_handler to covenant:80
      - "traefik.http.routers.covenantHandler.rule=Host(`cov.domain.tld`) && PathPrefix(`/cov_handler`)"
      - "traefik.http.routers.covenantHandler.service=covenantHandler@docker"
      - "traefik.http.routers.covenantHandler.entrypoints=https"
      - "traefik.http.services.covenantHandler.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
    driver: bridge